//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NET9-PC;Initial Catalog=RetailDB;Persist Security Info=True;User ID=s" +
            "a;Password=@Sa12345;MultipleActiveResultSets=True;Application Name=EntityFramewo" +
            "rk")]
        public string RetailDBConnectionString {
            get {
                return ((string)(this["RetailDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NET9-PC;Initial Catalog=DevfstPOS_StagingDB;User ID=sa")]
        public string DevfstPOS_StagingDBConnectionString {
            get {
                return ((string)(this["DevfstPOS_StagingDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NET26-PC;Initial Catalog=DevFstPOS_LiveDB;User ID=sa;Password=@Passwo" +
            "rdWQ")]
        public string DevFstPOS_LiveDBConnectionString {
            get {
                return ((string)(this["DevFstPOS_LiveDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NET26-PC;Initial Catalog=DevFstPOS_LiveDB05042019;Persist Security In" +
            "fo=True;User ID=sa;Password=@PasswordWQ")]
        public string DevFstPOS_LiveDB05042019ConnectionString {
            get {
                return ((string)(this["DevFstPOS_LiveDB05042019ConnectionString"]));
            }
        }
    }
}
