//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationRules_Rights_Detail
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string ObjectName { get; set; }
        public Nullable<bool> Viewable { get; set; }
        public Nullable<bool> Updatable { get; set; }
        public Nullable<bool> Deletable { get; set; }
    }
}
