//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationRule
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> Employee { get; set; }
        public Nullable<bool> Customer { get; set; }
        public Nullable<System.DateTime> dtstamp { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserType { get; set; }
        public Nullable<bool> Ibsales { get; set; }
        public Nullable<bool> Ibinventory { get; set; }
        public Nullable<bool> IbReports { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IbFinance { get; set; }
    }
}
