//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNF_Supplier
    {
        public int ID { get; set; }
        public string BusinessName { get; set; }
        public string ShortName { get; set; }
        public string BusinessType { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string LandLine { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> DefaultBankID { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> PaymentDays { get; set; }
    }
}
