//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNF_AppConfiguration
    {
        public int ID { get; set; }
        public string BusinessCode { get; set; }
        public string BusinessName { get; set; }
        public string BusinessShortName { get; set; }
        public string BusinessAddress { get; set; }
        public string LandLine { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string NotificationEmail { get; set; }
        public Nullable<bool> SalesNotification { get; set; }
        public Nullable<bool> SalesClosureNotification { get; set; }
        public Nullable<bool> DailyStockNotification { get; set; }
        public Nullable<int> PaymentDays { get; set; }
        public Nullable<bool> FirstPaymentNotification { get; set; }
        public Nullable<int> FirstNotificationDaysBefore { get; set; }
        public Nullable<bool> SecPaymentNotification { get; set; }
        public Nullable<int> SecNotificationDaysBefore { get; set; }
        public Nullable<bool> ThirdPaymentNotification { get; set; }
        public Nullable<int> ThirdNotificationDaysBefore { get; set; }
        public Nullable<bool> LowStockNotification { get; set; }
        public Nullable<int> DefaultBankID { get; set; }
        public string AccountNo { get; set; }
        public string NotificationEmailProfile { get; set; }
        public Nullable<bool> DailyExpenseNotification { get; set; }
        public string SMSGateWayURL { get; set; }
        public string SMSGateWayUser { get; set; }
        public string SMSGateWayPwd { get; set; }
        public Nullable<bool> SalesSMSNotification { get; set; }
        public string SMSCountryCode { get; set; }
    }
}
