//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POActivityDetail
    {
        public int ActivityID { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string SourceProductCode { get; set; }
        public Nullable<int> SourceProductQty { get; set; }
        public string TargetProductCode { get; set; }
        public Nullable<int> TargetProductQty { get; set; }
        public string ActivityType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string TargetLocation { get; set; }
        public string ActivityDetailDesc { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<decimal> NetDealerPrice { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
