//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POExpenseDetail
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public string ExpenseType { get; set; }
        public string ExpenseDesc { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AdjustedDate { get; set; }
    }
}
