//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POInventoryDetail
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> ProductDiscount { get; set; }
        public Nullable<decimal> DealerPrice { get; set; }
        public Nullable<decimal> NetProductDiscPct { get; set; }
        public Nullable<decimal> NetDealerPrice { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> DealerDiscPct { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsManualRate { get; set; }
    }
}
