//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POIncome
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<int> IncomeType { get; set; }
        public Nullable<decimal> PostingAmount { get; set; }
        public string Reference { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<bool> AdjustedInPOS { get; set; }
    }
}
