//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POPaymentDisbursement
    {
        public int ID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<int> PaymentBankID { get; set; }
        public string PaymentAccount { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> AdjustmentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Remarks { get; set; }
        public byte[] ReferenceDocument { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
