//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSaleDetail
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> CashInHand { get; set; }
        public Nullable<decimal> SaleClosure { get; set; }
        public string ClosureBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> AdjustedExpense { get; set; }
        public Nullable<decimal> TotalSale { get; set; }
        public Nullable<decimal> WithdrawCash { get; set; }
        public string WithdrawBy { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<decimal> AdjustedIncomeLoss { get; set; }
        public Nullable<decimal> POCashAdjustment { get; set; }
    }
}
