//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL_RateList
    {
        public string RateListId { get; set; }
        public string Name { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> dtStamp { get; set; }
        public string TerrId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> LoginHistoryId { get; set; }
        public int CCode { get; set; }
    }
}
