//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL_InvoiceDetail
    {
        public string InvoiceNo { get; set; }
        public int AutoID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> LoginHistoryId { get; set; }
        public string UserName { get; set; }
        public Nullable<double> ListRate { get; set; }
        public Nullable<double> DisP { get; set; }
        public Nullable<int> CCode { get; set; }
        public Nullable<double> NetRate { get; set; }
        public Nullable<double> DisAmt { get; set; }
        public string Status { get; set; }
        public Nullable<int> ReferenceID { get; set; }
    }
}
