//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK_productMaster
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Category { get; set; }
        public string UOMID { get; set; }
        public string StdPackingID { get; set; }
        public string PurchaserId { get; set; }
        public string Status { get; set; }
        public string BlockTrans { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> OpDate { get; set; }
        public Nullable<System.DateTime> dtStamp { get; set; }
        public Nullable<double> MinLevel { get; set; }
        public Nullable<double> MaxLevel { get; set; }
        public Nullable<double> ReOrdQty { get; set; }
        public string ACNo { get; set; }
        public string GroupId { get; set; }
        public string SubGroupId { get; set; }
        public Nullable<double> LeadTime { get; set; }
        public string MPCode { get; set; }
        public Nullable<int> LoginHistoryId { get; set; }
        public string UserName { get; set; }
        public Nullable<double> CT { get; set; }
        public Nullable<double> StdWeight { get; set; }
        public string Consumable { get; set; }
        public Nullable<double> ProdRate { get; set; }
        public string OldCode { get; set; }
        public int AutoId { get; set; }
        public string OldPurchaserId { get; set; }
        public string OldSupplierId { get; set; }
        public string ACNoCons { get; set; }
        public string ProductNameUrdu { get; set; }
        public string MatCateID { get; set; }
        public Nullable<int> CCode { get; set; }
        public Nullable<double> SRate { get; set; }
        public Nullable<double> DisP { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> POSShortcutBtn { get; set; }
        public Nullable<int> POSShortcutBtnSeq { get; set; }
    }
}
