//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFstPOSSuite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STK_UOM
    {
        public string Id { get; set; }
        public string UOMName { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> dtStamp { get; set; }
        public Nullable<int> LoginHistoryId { get; set; }
        public Nullable<int> CCode { get; set; }
    }
}
